esphome:
  name: esp-motor
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "f2099e28f39c3735783531e17f936689"

wifi:
  ssid: "noc.cisco.com"
  password: "aabbccddee"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Motor Fallback Hotspot"
    password: "2ZiN7usJKSFW"

captive_portal:


output:
  - platform: esp8266_pwm
    pin: GPIO4
    id: sh_speed_pin
  - platform: gpio
    pin: GPIO5
    id: sh_direction_pin1
    inverted: true
  - platform: gpio
    pin: GPIO16
    id: sh_direction_pin2
    inverted: true

cover:
  - platform: template
    name: "Simplehuman bin"
    id: lid
    open_action:
      - lambda: |-
           id(pulse_counter2) = 0; 
           id(pulsesM2) = 0; 
      - output.turn_on: sh_direction_pin2
      - output.turn_on: sh_speed_pin
      - output.set_level:
          id: sh_speed_pin
          level: 40%

      - delay: 2.5s
      - output.turn_off: sh_direction_pin2
      - output.turn_off: sh_speed_pin

      
    close_action:
      - lambda: |-
           id(pulse_counter1) = 0; 
           id(pulsesM1) = 0; 
      - output.turn_on: sh_direction_pin1
      - output.turn_on: sh_speed_pin
      - output.set_level:
          id: sh_speed_pin
          level: 40%
      - delay: 2.5s
      - output.turn_off: sh_direction_pin1
      - output.turn_off: sh_speed_pin


#    stop_action:
#      - output.turn_off: sh_direction_pin1
#      - output.turn_off: sh_direction_pin2
#      - output.turn_off: sh_speed_pin
    optimistic: true
    
sensor:
  - platform: pulse_counter
    id: pulse_counter1
    pin: 0
    name: "Motor Pulse 1"
    update_interval: .1s
    total:
      unit_of_measurement: 'cps'
      name: 'Pulses_M1'
      id: pulsesM1

  - platform: pulse_counter
    id: pulse_counter2
    pin: 14
    name: "Motor Pulse 2"
    update_interval: .1s
    total:
      unit_of_measurement: 'cps'
      name: 'Pulses_M2'
      id: pulsesM2